### ISSUE TITLE
Panic leads to stuck process/process not being closed.

### ISSUE THREAD

**Issue by dmeyer22** [fergusstrange/embedded-postgres#29]
Hey, awesome work so far, I tried the library, the issue I had is, if the test code is panicking the process will never be killed, even using recover did not work for me. The test were just stuck. And I had a postgres process blocking the configured port which needs to be killed manually. 

Any advice? 

What I tried from a setup point of view is the following, but the test still got stuck on panic and I had a process still running: 

```
func TestMain(m *testing.M) {
	testPostgresInstance = embeddedpostgres.NewDatabase()
	if err := testPostgresInstance.Start(); err != nil {
		panic(err)
	}
	defer func() {
		if err := testPostgresInstance.Stop(); err != nil {
			panic(err)
		}
	}()
	m.Run()
	if r := recover(); r != nil {
		if err := testPostgresInstance.Stop(); err != nil {
			panic(err)
		}
	}
}
```

**Comment by fergusstrange** [comment]
Hey @dmeyer22,

This should be possible to guard against using the following style of code. You can put it in a TestMain as well, just make sure your `m.Run()` sits inside an anonymous function block in order to defer the recovery function ahead of it.

I'll also add the following coverage to our tests in order to help others with this approach.

```
func shutdownDBAndFail(t *testing.T, err error, db *EmbeddedPostgres) {
	if db.started {
		if stopErr := db.Stop(); stopErr != nil {
			t.Errorf("Failed to shutdown server with error %s", stopErr)
		}
	}

	t.Errorf("Failed for version %s with error %s", db.config.version, err)
}

func Test_RecoversFromPanic(t *testing.T) {
	database := NewDatabase()
	if err := database.Start(); err != nil {
		shutdownDBAndFail(t, err, database)
	}

	func() {
		defer func() {
			if err := recover(); err != nil {
				shutdownDBAndFail(t, errors.New(err.(string)), database)
			}
		}()

		panic("oh no...")
	}()

	if err := database.Stop(); err != nil {
		shutdownDBAndFail(t, err, database)
	}
}
```

Let me know if you need any other help and I'd be happy to jump into more code with you.

**Comment by dmeyer22** [comment]
Thanks for the quick reply if I understand your suggestion correctly you mean like this in my case: 
```
func TestMain(m *testing.M) {
	testPostgresInstance := embeddedpostgres.NewDatabase()
	if err := testPostgresInstance.Start(); err != nil {
		panic(err)
	}
	defer func() {
		if err := recover(); err != nil {
			if err := testPostgresInstance.Stop(); err != nil {
				panic(err)
			}
		}
	}()
	func() {
		m.Run()
	}()
}
```

I can confirm you suggestion works but not together with `m.Run()` it still gets stuck for me.

**Comment by fergusstrange** [comment]
Hi @dmeyer22,

Apologies I'd actually forgotten that TestMain throws an [unrecoverable panic](https://github.com/golang/go/issues/37206) if there is a panic inside any of the test code. This is by design, if somewhat inconvenient at times.

The general approach I've seen for this is something as follows, which can easily be tweaked for cleaner separation of tests and readability.

```
var allTests = []func(*testing.T){
	func(t *testing.T) {
		TheApp()
	},
	func(t *testing.T) {
		assert.Equal(t, 1, 1)
	},
}

func Test_TestSuite(t *testing.T) {
	isStarted := false
	testPostgresInstance := embeddedpostgres.NewDatabase()

	if err := testPostgresInstance.Start(); err != nil {
		panic(err)
	}

	isStarted = true

	for _, testToRun := range allTests {
		func() {
			defer func() {
				if err := recover(); err != nil {
					t.Error(err)
					t.Fail()
				}
			}()
			testToRun(t)
		}()
	}

	if isStarted {
		if err := testPostgresInstance.Stop(); err != nil {
			panic(err)
		}
	}
}

func TheApp() {
	panic("Oh shi...")
}
``` 

Let me know what you think?

**Comment by fergusstrange** [comment]
I updated to include actually using the t.Run() function which really improves readability in certain IDEs.
