### ISSUE TITLE
Move away from https://github.com/mholt/archiver

### ISSUE THREAD

**Issue by naveensrinivasan** [fergusstrange/embedded-postgres#43]
The https://github.com/mholt/archiver repository hasn't been getting much attention. https://github.com/mholt/archiver/issues/283

Especially with the CVE like this and when it isn't maintained https://deps.dev/go/github.com%2Fmholt%2Farchiver%2Fv3 it gets harder for the downstream. 

A suggestion would be is to fork that repository and use the fork.

Thank you!

**Comment by fergusstrange** [comment]
Thanks @naveensrinivasan,

This has been on the radar for a while and I will have a look at removing both dependencies and utilising a vendored https://github.com/xi2/xz in order to do our decompression. This will actually mean we have zero dependencies for production code as well as a side benefit.

**Comment by naveensrinivasan** [comment]
Great! Thanks for the update. This is a great framework https://slsa.dev backed by LinuxFoundation

**Comment by fergusstrange** [comment]
Thanks @naveensrinivasan release cut https://github.com/fergusstrange/embedded-postgres/releases/tag/v1.11.0
