### ISSUE TITLE
Support Intel and Arm MAC

### ISSUE THREAD

**Issue by gedw99** [fergusstrange/embedded-postgres#56]
Note: this issue is created to isolate from the other issues that per affected on Linux and windows.

Look into support for better logging on new Mac ARM, with rosetta emulation support by default.

Longer term support for Mac ARM when the packages are available on Maven.

**Comment by goguson** [comment]
Personally,i can run tests, but currently I am unable to debug code with embedded postgres running

**Comment by goguson** [comment]
> Looks like some fat jars have been published so I'll be looking into adding support for the rosetta emulation soon. I am however without a MacBook M1 and as yet no support in the cloud so unable to test this. I'm looking for a volunteer to collaborate on that side of things.
> 
> Hands up ✋ if you are interested.

I can help you with my M1 I guess :D Lemme know when you have time and how to contact you further

**Comment by goguson** [comment]
[Here](https://github.com/fergusstrange/embedded-postgres/pull/62) I added support for 14.1.0 binaries, which solved my issue with running db in debug mode on M1 Mac, which IMO is important. Please take a look @fergusstrange.

**Comment by fergusstrange** [comment]
I couldn't work out how to add you directly to the Pull Request @goguson but here is the upgraded Postgres Versions outside of v14 (which I believe are not actually fat binaries and thus shouldn't work still on Mac M1) https://github.com/fergusstrange/embedded-postgres/pull/63/commits/1ad81be9145831bdf3a1d54eacd7c23edcc18ebb

If you could just do a `go test ./...` inside the repository root, examples and platform-test directories and let me know the results that would be awesome.

I think we may need something akin to https://github.com/zonkyio/embedded-postgres/commit/ce6256ea4fced93b378a0f92cdc54f92a35b80cc if the above doesn't work in order to get previous versions running with Rosetta support, but again, I'll need your help here to determine that!

Thanks again for all the help!

**Comment by goguson** [comment]
> I couldn't work out how to add you directly to the Pull Request @goguson but here is the upgraded Postgres Versions outside of v14 (which I believe are not actually fat binaries and thus shouldn't work still on Mac M1) [1ad81be](https://github.com/fergusstrange/embedded-postgres/commit/1ad81be9145831bdf3a1d54eacd7c23edcc18ebb)
> 
> If you could just do a `go test ./...` inside the repository root, examples and platform-test directories and let me know the results that would be awesome.
> 
> I think we may need something akin to [zonkyio/embedded-postgres@ce6256e](https://github.com/zonkyio/embedded-postgres/commit/ce6256ea4fced93b378a0f92cdc54f92a35b80cc) if the above doesn't work in order to get previous versions running with Rosetta support, but again, I'll need your help here to determine that!
> 
> Thanks again for all the help!

Today/tomorrow I will check and let you know about the result

**Comment by fergusstrange** [comment]
@goguson I've merged the PR and releasing a [new version](https://github.com/fergusstrange/embedded-postgres/releases/tag/v1.13.0) which you can now use for testing. Let me know how you go and if I need to put in a bit more work to get the older versions working.

**Comment by fergusstrange** [comment]
Hey @goguson closing this, let me know if we need to re-open!
