### ISSUE TITLE
Add error info when 'unable to init db'

### ISSUE THREAD

**Issue by dor-utila** [fergusstrange/embedded-postgres#78]
Currently, I get this error, without any useful information:
```
panic: localpg: failed to start PgSQL: unable to init database using: /tmp/go_embedded_pgsql_binaries_3773798719/bin/initdb -A password -U username -D /tmp/go_embedded_pgsql_runtime_2105005878/data --pwfile=/tmp/go_embedded_pgsql_runtime_2105005878/pwfile --locale=en_US.UTF-8
```

**Comment by fergusstrange** [comment]
Hey @OnigiriJack what embedded-postgres version/tag are you running? I assume it's https://github.com/fergusstrange/embedded-postgres/releases/tag/v1.5.0 as I think that matched Postgres 12.6.

**Comment by fergusstrange** [comment]
Just confirmed this version is from before we had Alpine linux support, which was introduced in the very next version [1.6.0](https://github.com/fergusstrange/embedded-postgres/releases/tag/v1.6.0).

There's been lots releases since this even, so I'd recommend trying to stay up to date to get the best support. You can see all releases [here](https://github.com/fergusstrange/embedded-postgres/releases).

Thanks
